### ISSUE TITLE
[BUG] - filter menu hiden komt terug wanneer sorteer optie gewijzigd wordt

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-rich-data#20]
**Omschrijf het probleem**
Filter komt vanzelf terug te voorschijn bij het filteren, wanneer de toggle eerst was afgezet. 

**Hoe te reproduceren**

1. Filter togglen zodanig dat filter menu verdwijnt
2. Sorteren > kies een andere optie dan de huidige selectie
3. Filter komt terug te voorschijn (dit is al ongewenst gedrag)
4. Om filter terug weg te laten doen, moet je nu 2x op toggle duwen zelfs (ook ongewenst gedrag)

**Gewenst gedrag**
keuze om filter weg te laten moet onthouden worden ongeacht de sorteer wijziging

**Screenshots**
niet duidelijk in screenshots, maar je kan zelf zien op https://inspraak-ontwikkel.omgeving.vlaanderen.be/ 
<img width="1336" alt="Screenshot 2021-01-15 at 17 15 44" src="https://user-images.githubusercontent.com/8820456/104751180-51bb5400-5755-11eb-833b-6cc9c95f7d4d.png">

**Omgeving (gelieve aan te vullen):**
 - Browser chrome/safari

 - Versie component 1.0.3

**Comment by coemans** [comment]
Probleem blijkt niet meer reproduceerbaar in de laatste versie. Indien het probleem zich applicatief alsnog stelt, mag issue opnieuw geopend worden.
