### ISSUE TITLE
[BUG] - Er wordt vanuit gegaan dat de filter slot altijd zal opgevuld worden met een component die een data-vl-alt attribuut heeft

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-rich-data#30]
**Omschrijf het probleem**
In processSearchFilter gebeurt het volgende: `this.__searchFilter.setAttribute('data-vl-alt', '');` waarbij
```
  get __searchFilter() {
    return this.querySelector('[slot="filter"]');
  }
```

Dit gaat ervan uit dat het filter slot altijd wordt opgevuld met een component die een `data-vl-alt` attribuut heeft.

We hadden een scenario waarbij de elementen die het filter slot innamen als volgt er konden uitzien:
```
<div slot="filter"><vl-loader id="loader-search-form"></vl-loader></div>
```
of

```
<div slot="filter"><div is="vl-search-filter"><form>...</form></div></div>
```

Hierbij werd de data-vl-alt dus op de omliggende div gezet ipv de `vl-search-filter`.

Indien er altijd een `vl-search-filter` verwacht wordt, dan zou die in de shadowRoot moeten komen en daar de `data-vl-alt` gezet moeten worden.

Indien dat niet per se zo is, zou die `data-vl-alt` niet gezet moeten worden door de component zelf.

**Comment by coemans** [comment]
Zie #26. De `vl-search-filter` is nu rechtstreeks onderdeel van de API. De `vl-search-filter` bevat een `data-vl-alt` attribuut, waardoor die assumptie geen probleem is.

Ik sluit voorlopig ticket af, indien het alsnog een probleem vormt verneem ik het graag.

**Comment by SBylemans** [comment]
@coemans we hebben dit al in een PR opgelost. We hebben dit vorige week nog besproken? De selector voor searchFilter is aangepast in die PR.

**Comment by coemans** [comment]
Te bekijken in de PR, ik dacht dat de conclusie was dat er geen nood was aan een wrapper element waardoor er op zich geen probleem meer was. Zal blijken uit de PR, al zullen we die waarschijnlijk best opsplitsen om het overzicht te bewaren.
