### ISSUE TITLE
[BUG] - Responsive issues

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-rich-data#33]
**Omschrijf het probleem**
Search-filter in combinatie met de vl-select met deletable items zorgt er voor dat de responsiveness niet meer werkt.

Nog meerdere issues:

1. scrollable background
2. filter meerdere keren openen en sluiten append telkens een titel aan de huidige titel
<img width="494" alt="Screenshot 2021-04-23 at 09 52 01" src="https://user-images.githubusercontent.com/8820456/115838119-a0921d00-a419-11eb-8af6-992f4d4f7568.png">
3. deletable items in de vl-select worden niet terug in de select geplaatst bij het heropenen van de filter. Waardoor de filter functionaliteit eigenlijk breekt wanneer je een 2e keer wil filteren met reeds geselecteerde items. 

**Hoe te reproduceren**
Zie demo pagina in branch https://github.com/milieuinfo/webcomponent-vl-ui-rich-data/tree/responsive-issues

**Comment by coemans** [comment]
Probleem dat de titel meermaals getoond werd, is opgelost in PR [#58](https://github.com/milieuinfo/webcomponent-vl-ui-search-filter/pull/58) en PR #34.

**Comment by coemans** [comment]
Probleem dat de achterliggende pagina scrollable is wanneer de filter geopend staat op mobiele toestellen werd opgelost in PR #35.

**Comment by coemans** [comment]
Probleem in combinatie met vl-ui-multiselect werd opgelost in PR [#60](https://github.com/milieuinfo/webcomponent-vl-ui-search-filter/pull/60).
